--
-- Tables for the pregnancy care module
--
CREATE TABLE PREGNANCY (
  PREG_ID int(11) NOT NULL AUTO_INCREMENT,
  PREG_NR int(11) NOT NULL,
  PREG_PAT_ID int(11) NOT NULL,
  PREG_LMP date NOT NULL DEFAULT '2016-01-01',
  PREG_CALC_DELIVERY date NOT NULL DEFAULT '2016-01-01',
  PREG_ACTIVE varchar(1) NOT NULL DEFAULT 'Y',
  INDEX ( PREG_PAT_ID  ) ,
  PRIMARY KEY (PREG_ID)
) ENGINE=MyISAM;

CREATE TABLE PREGNANCYDELIVERY (
  PDEL_ID int(11) NOT NULL AUTO_INCREMENT COMMENT 'the id of the table',
  PDEL_ADM_ID int(11) NOT NULL COMMENT 'the id of the pregnancyadmission record referred to',
  PDEL_DATE_DEL  datetime default NULL,
  PDEL_DLT_ID_A  char(1) default NULL,
  PDEL_DRT_ID_A char(1) DEFAULT NULL COMMENT 'reference to deliverytyperesult table',
  PDEL_WEIGHT float NOT NULL COMMENT 'the weight of the newborn',
  PDEL_SEX char(1) NOT NULL DEFAULT 'F',
  INDEX ( PDEL_ADM_ID ) ,
  INDEX ( PDEL_DLT_ID_A ),
  INDEX ( PDEL_DRT_ID_A ) ,
  PRIMARY KEY (PDEL_ID)
) ENGINE=MyISAM;

CREATE TABLE PREGNANCYEXAM (
  PREGEX_ID varchar(10) NOT NULL COMMENT 'the id of the pregnancy exam',
  PREGEX_DESC varchar(100) NOT NULL COMMENT 'the description of the pregnancy exam',
  PREGEX_TYPE tinyint(2) NOT NULL DEFAULT '-1' COMMENT 'the type the exam is used for (-1 = prenatal, 1= postnatal, 0= both)',
  PREGEX_DEFAULT varchar(50) DEFAULT NULL COMMENT 'the default value of the pregnancy exam',
  PREGEX_VALUES varchar(255) DEFAULT NULL,
  PRIMARY KEY (PREGEX_ID)
) ENGINE=MyISAM;

CREATE TABLE PREGNANCYEXAMRESULT (
  PEXRES_ID int(11) NOT NULL AUTO_INCREMENT COMMENT 'the id of the pregnancy exam result',
  PEXRES_PVIS_ID int(11) NOT NULL,
  PEXRES_PREGEX_ID varchar(10) NOT NULL,
  PEXRES_OUTCOME varchar(50) NOT NULL,
  INDEX ( PEXRES_PVIS_ID ) ,
  INDEX ( PEXRES_PREGEX_ID ) ,
  PRIMARY KEY (PEXRES_ID)
) ENGINE=MyISAM;

CREATE TABLE PREGNANCYVISIT (
  PVIS_ID int(11) NOT NULL AUTO_INCREMENT,
  PVIS_PREG_ID int(11) NOT NULL,
  PVIS_DATE datetime NOT NULL DEFAULT '2016-01-01 00:00:00',
  PVIS_NEXTDATE datetime DEFAULT NULL,
  PVIS_PTT_ID_A varchar(10) DEFAULT NULL,
  PVIS_NOTE text,
  PVIS_TYPE tinyint(2) NOT NULL DEFAULT '-1',
  INDEX ( PVIS_PREG_ID ) ,
  INDEX ( PVIS_PTT_ID_A ) ,
  PRIMARY KEY (PVIS_ID)
) ENGINE=MyISAM;

--
-- Foreign keys
--
ALTER TABLE PREGNANCY 
	ADD CONSTRAINT FK_PREGNANCY_PATIENT 
	FOREIGN KEY (PREG_PAT_ID) 
	REFERENCES PATIENT (PAT_ID);

ALTER TABLE PREGNANCYDELIVERY 
	ADD CONSTRAINT FK_PREGNANCYDELIVERY_ADMISSION
	FOREIGN KEY (PDEL_ADM_ID) 
	REFERENCES ADMISSION (ADM_ID);

ALTER TABLE PREGNANCYDELIVERY 
	ADD CONSTRAINT FK_PREGNANCYDELIVERY_DELIVERYRESULTTYPE
	FOREIGN KEY (PDEL_DRT_ID_A) 
	REFERENCES DELIVERYRESULTTYPE (DRT_ID_A);

	
ALTER TABLE PREGNANCYDELIVERY 
	ADD CONSTRAINT FK_PREGNANCYDELIVERY_DELIVERYTYPE
	FOREIGN KEY (PDEL_DLT_ID_A) 
	REFERENCES DELIVERYTYPE (DLT_ID_A);

ALTER TABLE PREGNANCYEXAMRESULT 
	ADD CONSTRAINT FK_PREGNANCYEXAMRESULT_PREGNANCYEXAM
	FOREIGN KEY (PEXRES_PREGEX_ID) 
	REFERENCES PREGNANCYEXAM (PREGEX_ID);

ALTER TABLE PREGNANCYEXAMRESULT 
	ADD CONSTRAINT FK_PREGNANCYEXAMRESULT_PREGNANCYVISIT
	FOREIGN KEY (PEXRES_PVIS_ID) 
	REFERENCES PREGNANCYVISIT (PVIS_ID);

ALTER TABLE PREGNANCYVISIT
	ADD CONSTRAINT FK_PREGNANCYVISIT_PREGNANCY
	FOREIGN KEY (PVIS_PREG_ID) 
	REFERENCES PREGNANCY (PREG_ID);

ALTER TABLE PREGNANCYVISIT
	ADD CONSTRAINT FK_PREGNANCYVISIT_PREGNANTTREATMENTTYPE
	FOREIGN KEY (PVIS_PTT_ID_A) 
	REFERENCES PREGNANTTREATMENTTYPE (PTT_ID_A);


--
-- Dumping data for table 'MENUITEM'
--
INSERT INTO `MENUITEM` (`MNI_ID_A`,`MNI_BTN_LABEL`,`MNI_LABEL`,`MNI_TOOLTIP`,`MNI_SHORTCUT`,`MNI_SUBMENU`,`MNI_CLASS`,`MNI_IS_SUBMENU`,`MNI_POSITION`) VALUES 
 ('pregnancy','angal.menu.btn.pregnancy','angal.menu.pregnancy','x','P','main','org.isf.pregnancy.gui.PregnancyCareBrowser','N',5),
 ('pregnancyexam','angal.menu.btn.pregnancyexam','angal.menu.pregnancy','x','P','generaldata','org.isf.pregnancyexam.gui.PregnancyExamBrowser','N',4);

--
-- Dumping data for table 'GROUPMENU'
--
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES 
('admin','pregnancy','Y'),
('admin','pregnancyexam','Y');

--
-- Pregnancy exams evaluated outside the laboratory
--
INSERT INTO PREGNANCYEXAM (PREGEX_ID, PREGEX_DESC, PREGEX_TYPE, PREGEX_DEFAULT, PREGEX_VALUES) VALUES
('MW', 'Mothers weight', 0, '', ''),
('BP', 'Blood Pressure', 0, '', ''),
('FHR', 'Fetal Heart Rate', -1, '', '');
