INSERT INTO MENUITEM VALUES ('mortuary', 'angal.menu.btn.mortuary', 'angal.menu.mortuary', 'x', 'M', 'main', 'org.isf.mortuary.gui.MortuaryBrowser','N', 9);
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','mortuary','Y');

/*
 * Death Reason submenu in general data / types
 */

INSERT INTO MENUITEM VALUES ('deathreason', 'angal.menu.btn.deathreason', 'angal.menu.deathreason', 'x', 'D', 'types', 'org.isf.mortuary.gui.DeathReasonBrowser','N', 13);
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','deathreason','Y');

/*
 * Mortuary Price submenu in general data 
 */

INSERT INTO MENUITEM VALUES ('mortuaryprice', 'angal.menu.btn.mortuaryprice', 'angal.menu.mortuaryprice', 'x', 'P', 'generaldata', 'org.isf.mortuary.gui.MortuaryPriceBrowser','N', 5);
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','mortuaryprice','Y');

INSERT INTO parameters (PRMS_CODE, PRMS_VALUE, PRMS_DEFAULT_VALUE, PRMS_DESCRIPTION, PRMS_CREATE_BY, PRMS_MODIFY_BY, PRMS_CREATE_DATE, PRMS_MODIFY_DATE, PRMS_DELETED_BY, PRMS_DELETED_DATE, PRMS_DELETED) VALUES
	('ENABLEMORTUARYMODULE', '@false', '@false', 'Enable motuary module', 'admin', NULL, '2019-07-20 10:46:28', NULL, NULL, NULL, NULL);
INSERT INTO parameters (PRMS_CODE, PRMS_VALUE, PRMS_DEFAULT_VALUE, PRMS_DESCRIPTION, PRMS_CREATE_BY, PRMS_MODIFY_BY, PRMS_CREATE_DATE, PRMS_MODIFY_DATE, PRMS_DELETED_BY, PRMS_DELETED_DATE, PRMS_DELETED) VALUES
	('CERTIFICATEOFDEATH', 'certificateOfDeath', 'certificateOfDeath', 'jasper file of certificate model', 'admin', NULL, '2019-08-01 15:18:28', NULL, NULL, NULL, NULL);


DROP TABLE IF EXISTS MOTIF_DECES;
CREATE TABLE MOTIF_DECES  (
	MOTIF_ID int NOT NULL auto_increment,
	MOTIF_CODE varchar(5) NOT NULL UNIQUE,
	MOTIF_DESCRIPTION varchar(150) CHARACTER SET utf8,	
	PRIMARY KEY  ( MOTIF_ID )
) ENGINE=MyISAM;

DROP TABLE IF EXISTS PLAGE_PRIX_MORGUE;
CREATE TABLE PLAGE_PRIX_MORGUE(
	PLAGE_PRIX_ID int NOT NULL auto_increment,
	NB_JOUR_MIN int,
	NB_JOUR_MAX int,
	PRIX_JOURNALIER float,
	CODE varchar(10) CHARACTER SET utf8 UNIQUE,
	DESCRIPTION varchar(50) CHARACTER SET utf8,
	PRIMARY KEY (PLAGE_PRIX_ID)
)ENGINE=MyISAM;

DROP TABLE IF EXISTS DECES;
CREATE TABLE DECES (
	DECES_ID int NOT NULL auto_increment PRIMARY KEY,
	DECES_CASIER varchar(50) CHARACTER SET utf8,
	DECES_PAT_ID int NOT NULL UNIQUE,
	DECES_PROVENANCE varchar(50) CHARACTER SET utf8,
	DECES_DATE datetime,
	DECES_LIEU varchar(50) CHARACTER SET utf8,
	DECES_DATE_ENTREE datetime,
	DECES_DATE_SORTIE datetime,
	DECES_DATE_SORTIE_PROVISOIRE datetime,
	DECES_MOTIF_ID int NOT NULL,
	DECES_NOM_DECLARANT varchar(50) CHARACTER SET utf8,
	DECES_TEL_DECLARANT varchar(15),
	DECES_NID_DECLARANT varchar(30),
	DECES_NOM_FAMILLE varchar(50) CHARACTER SET utf8,
	DECES_TEL_FAMILLE varchar(15),
	DECES_NID_FAMILLE varchar(30),
	DECES_DELETED int NOT NULL default 0,
	FOREIGN KEY FK_PAT(DECES_PAT_ID) REFERENCES PATIENT(PAT_ID),
	FOREIGN KEY FK_MOTIF(DECES_MOTIF_ID) REFERENCES MOTIF_DECES(MOTIF_ID)
)ENGINE=MyISAM;

ALTER TABLE MOTIF_DECES ADD MOTIF_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE MOTIF_DECES ADD MOTIF_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE MOTIF_DECES ADD MOTIF_CREATE_DATE datetime NULL;
ALTER TABLE MOTIF_DECES ADD MOTIF_MODIFY_DATE datetime NULL;

ALTER TABLE PLAGE_PRIX_MORGUE ADD PLAGE_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE PLAGE_PRIX_MORGUE ADD PLAGE_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE PLAGE_PRIX_MORGUE ADD PLAGE_CREATE_DATE datetime NULL;
ALTER TABLE PLAGE_PRIX_MORGUE ADD PLAGE_MODIFY_DATE datetime NULL;

ALTER TABLE DECES ADD DECES_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE DECES ADD DECES_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE DECES ADD DECES_CREATE_DATE datetime NULL;
ALTER TABLE DECES ADD DECES_MODIFY_DATE datetime NULL;

	
