UPDATE `MENUITEM` SET `MNI_POSITION`=0 WHERE `MNI_ID_A`='file';
UPDATE `MENUITEM` SET `MNI_POSITION`=1 WHERE `MNI_ID_A`='generaldata';
UPDATE `MENUITEM` SET `MNI_POSITION`=2 WHERE `MNI_ID_A`='opd';
UPDATE `MENUITEM` SET `MNI_POSITION`=3 WHERE `MNI_ID_A`='pharmacy';
UPDATE `MENUITEM` SET `MNI_POSITION`=4 WHERE `MNI_ID_A`='laboratory';
UPDATE `MENUITEM` SET `MNI_POSITION`=5 WHERE `MNI_ID_A`='pregnancy';
UPDATE `MENUITEM` SET `MNI_POSITION`=6 WHERE `MNI_ID_A`='accounting';
UPDATE `MENUITEM` SET `MNI_POSITION`=7 WHERE `MNI_ID_A`='admission';
UPDATE `MENUITEM` SET `MNI_POSITION`=8 WHERE `MNI_ID_A`='patientvaccine';
UPDATE `MENUITEM` SET `MNI_POSITION`=9 WHERE `MNI_ID_A`='mortuary';
UPDATE `MENUITEM` SET `MNI_POSITION`=10 WHERE `MNI_ID_A`='statistics';
UPDATE `MENUITEM` SET `MNI_POSITION`=11 WHERE `MNI_ID_A`='printing';
UPDATE `MENUITEM` SET `MNI_POSITION`=12 WHERE `MNI_ID_A`='help';
UPDATE `MENUITEM` SET `MNI_POSITION`=13 WHERE `MNI_ID_A`='communication';

INSERT INTO parameters (PRMS_CODE, PRMS_VALUE, PRMS_DEFAULT_VALUE, PRMS_DESCRIPTION, PRMS_CREATE_BY, PRMS_MODIFY_BY, PRMS_CREATE_DATE, PRMS_MODIFY_DATE, PRMS_DELETED_BY, PRMS_DELETED_DATE, PRMS_DELETED) VALUES
	('ENABLEPRICECONTROL', '@false', '@false', 'Enable price control', 'admin', NULL, '2019-08-16 11:44:28', NULL, NULL, NULL, NULL);

INSERT INTO parameters (PRMS_CODE, PRMS_VALUE, PRMS_DEFAULT_VALUE, PRMS_DESCRIPTION, PRMS_CREATE_BY, PRMS_MODIFY_BY, PRMS_CREATE_DATE, PRMS_MODIFY_DATE, PRMS_DELETED_BY, PRMS_DELETED_DATE, PRMS_DELETED) VALUES
	('ENABLEBILLEDITOVERMONTH', '@false', '@false', 'Enable bill edit after a month', 'admin', NULL, '2019-08-17 09:35:28', NULL, NULL, NULL, NULL);

INSERT INTO parameters (PRMS_CODE, PRMS_VALUE, PRMS_DEFAULT_VALUE, PRMS_DESCRIPTION, PRMS_CREATE_BY, PRMS_MODIFY_BY, PRMS_CREATE_DATE, PRMS_MODIFY_DATE, PRMS_DELETED_BY, PRMS_DELETED_DATE, PRMS_DELETED) VALUES
	('ENABLEMEDICALREFUND', '@false', '@false', 'Enable refunding medicals', 'admin', NULL, '2019-08-27 10:55:28', NULL, NULL, NULL, NULL);

INSERT INTO parameters (PRMS_CODE, PRMS_VALUE, PRMS_DEFAULT_VALUE, PRMS_DESCRIPTION, PRMS_CREATE_BY, PRMS_MODIFY_BY, PRMS_CREATE_DATE, PRMS_MODIFY_DATE, PRMS_DELETED_BY, PRMS_DELETED_DATE, PRMS_DELETED) VALUES
	('ENABLEBILLESTIMATE', '@false', '@false', 'Enable bills estimates', 'admin', NULL, '2019-08-27 11:55:28', NULL, NULL, NULL, NULL);




