ALTER TABLE patient ADD PAT_BIRTH_PLACE varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "" AFTER PAT_BDATE;
ALTER TABLE patient ADD PAT_GEOGRAPHIC_AREA varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";

ALTER TABLE pregnancydelivery ADD PDEL_FATHER_NAME varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE pregnancydelivery ADD PDEL_FATHER_OCCUPATION varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE pregnancydelivery ADD PDEL_FATHER_RESIDENCE varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE pregnancydelivery ADD PDEL_FATHER_AGE INT NULL DEFAULT 0;
ALTER TABLE pregnancydelivery ADD PDEL_FATHER_BIRTH_PLACE varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";

ALTER TABLE pregnancydelivery ADD PDEL_CHILD_NAME varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";