ALTER TABLE bills ADD BLL_GARANTE varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";


CREATE TABLE city  (
	CITY_LIBELLE varchar(100) NOT NULL,
	UNIQUE KEY CITY_LIBELLE (CITY_LIBELLE)
);

CREATE TABLE occupation (
  OCC_LIBELLE varchar(100) NOT NULL,
  UNIQUE KEY OCC_LIBELLE (OCC_LIBELLE)
)