CREATE TABLE EXAMS_MEDICALS(
    `ID` int(15) not null auto_increment, 
    `MDSR_ID` int(11) not null, 
	`EXA_ID_A` varchar(10)not null, 
    `QUANTITY` int(10) DEFAULT 0,
	`NOTE` varchar(255),
    Foreign Key(`MDSR_ID`) references MEDICALDSR(`MDSR_ID`),
	Foreign Key(`EXA_ID_A`) references EXAM(`EXA_ID_A`),
    PRIMARY KEY (`ID`)
)  ENGINE=MyISAM;

ALTER TABLE `EXAMS_MEDICALS`
  ADD CONSTRAINT `FK_MEDICALDSR` FOREIGN KEY (`MDSR_ID`) REFERENCES `MEDICALDSR`(`MDSR_ID`) ON DELETE CASCADE;
  
ALTER TABLE `EXAMS_MEDICALS`
  ADD CONSTRAINT `FK_EXAM` FOREIGN KEY (`EXA_ID_A`) REFERENCES `EXAM`(`EXA_ID_A`) ON DELETE CASCADE ON UPDATE CASCADE;