CREATE TABLE IF NOT EXISTS REDUCTIONPLAN (
  RP_ID INT(11) NOT NULL AUTO_INCREMENT,
  RP_DESCRIPTION varchar(100) NOT NULL,
  RP_OPERATIONRATE float NOT NULL,
  RP_MEDICALRATE float NOT NULL,
  RP_EXAMRATE float NOT NULL,
  RP_OTHERRATE float NOT NULL,
  RP_DATE datetime NOT NULL,
  RP_UPDATE datetime NOT NULL,
  PRIMARY KEY (RP_ID)
);

CREATE TABLE IF NOT EXISTS EXAMSREDUCTION (
  ER_RP_ID INT(11) NOT NULL,
  ER_EXA_ID_A VARCHAR(10) NOT NULL,
  ER_REDUCTIONRATE float NOT NULL,
  PRIMARY KEY (ER_RP_ID, ER_EXA_ID_A)
);

CREATE TABLE IF NOT EXISTS MEDICALSREDUCTION (
  MR_RP_ID INT(11) NOT NULL,
  MR_MED_ID INT(11) NOT NULL,
  MR_REDUCTIONRATE float NOT NULL,
  PRIMARY KEY (MR_RP_ID, MR_MED_ID)
);

CREATE TABLE IF NOT EXISTS OPERATIONSREDUCTION (
  OPR_RP_ID INT(11) NOT NULL,
  OPR_OPE_ID_A INT(11) NOT NULL,
  OPR_REDUCTIONRATE float NOT NULL,
  PRIMARY KEY (OPR_RP_ID, OPR_OPE_ID_A)
);

CREATE TABLE IF NOT EXISTS OTHERREDUCTION (
  OTR_RP_ID INT(11) NOT NULL,
  OTR_OTH_ID INT(11) NOT NULL,
  OTR_REDUCTIONRATE float NOT NULL,
  PRIMARY KEY (OTR_RP_ID, OTR_OTH_ID)
);

ALTER TABLE  PATIENT ADD  PAT_RP_ID INT DEFAULT  '0';

ALTER TABLE  PATIENT ADD  PAT_LST_ID INT DEFAULT  '0';

INSERT INTO MENUITEM VALUES ('reductionplan','angal.menu.btn.reductionplan','angal.menu.reductionplan','x','R','generaldata','org.isf.reduction.gui.ReductionPlanBrowser','N',10);
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','reductionplan','Y');

ALTER TABLE  `user` ADD  `US_WRD_ID_A` VARCHAR( 1 ) NULL;
ALTER TABLE  `billitems` ADD  `BLI_MED_ID` INT NULL;




