ALTER TABLE patient ADD PAT_AFFILIATED_PERSON INT(11) NULL default NULL;
ALTER TABLE patient ADD PAT_IS_HEAD_AFFILIATION boolean not NULL default 0;
ALTER TABLE bills ADD BLL_RP_ID INT(11) NULL default NULL;
ALTER TABLE bills ADD BLL_PAT_AFFILIATED_PERSON INT(11) NULL default NULL;
ALTER TABLE billitems ADD BLI_ITEM_AMOUNT_BRUT double NULL;