ALTER TABLE user ADD US_FIRSTNAME varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE user ADD US_SURNAME varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE user ADD US_PHONE varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";

ALTER TABLE billpayments ADD BLP_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE billpayments ADD BLP_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE billpayments ADD BLP_CREATE_DATE datetime NULL;
ALTER TABLE billpayments ADD BLP_MODIFY_DATE datetime NULL;

ALTER TABLE bills ADD BLL_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE bills ADD BLL_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE bills ADD BLL_CREATE_DATE datetime NULL;
ALTER TABLE bills ADD BLL_MODIFY_DATE datetime NULL;

ALTER TABLE admission ADD ADM_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE admission ADD ADM_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE admission ADD ADM_CREATE_DATE datetime NULL;
ALTER TABLE admission ADD ADM_MODIFY_DATE datetime NULL;

ALTER TABLE laboratory ADD LAB_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE laboratory ADD LAB_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE laboratory ADD LAB_CREATE_DATE datetime NULL;
ALTER TABLE laboratory ADD LAB_MODIFY_DATE datetime NULL;

ALTER TABLE medicaldsrstockmov ADD MMV_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE medicaldsrstockmov ADD MMV_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE medicaldsrstockmov ADD MMV_CREATE_DATE datetime NULL;
ALTER TABLE medicaldsrstockmov ADD MMV_MODIFY_DATE datetime NULL;

ALTER TABLE medicaldsrstockmovward ADD MMVN_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE medicaldsrstockmovward ADD MMVN_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE medicaldsrstockmovward ADD MMVN_CREATE_DATE datetime NULL;
ALTER TABLE medicaldsrstockmovward ADD MMVN_MODIFY_DATE datetime NULL;

ALTER TABLE medicaldsr ADD MDSR_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE medicaldsr ADD MDSR_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE medicaldsr ADD MDSR_CREATE_DATE datetime NULL;
ALTER TABLE medicaldsr ADD MDSR_MODIFY_DATE datetime NULL;

ALTER TABLE medicaldsrward ADD MDSRWRD_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE medicaldsrward ADD MDSRWRD_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE medicaldsrward ADD MDSRWRD_CREATE_DATE datetime NULL;
ALTER TABLE medicaldsrward ADD MDSRWRD_MODIFY_DATE datetime NULL;

ALTER TABLE medicaldsrinventory ADD INVT_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE medicaldsrinventory ADD INVT_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE medicaldsrinventory ADD INVT_CREATE_DATE datetime NULL;
ALTER TABLE medicaldsrinventory ADD INVT_MODIFY_DATE datetime NULL;

ALTER TABLE medicaldsrinventoryrow ADD INVTR_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE medicaldsrinventoryrow ADD INVTR_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE medicaldsrinventoryrow ADD INVTR_CREATE_DATE datetime NULL;
ALTER TABLE medicaldsrinventoryrow ADD INVTR_MODIFY_DATE datetime NULL;

ALTER TABLE operationrow ADD OPER_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE operationrow ADD OPER_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE operationrow ADD OPER_CREATE_DATE datetime NULL;
ALTER TABLE operationrow ADD OPER_MODIFY_DATE datetime NULL;

ALTER TABLE opd ADD OPD_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE opd ADD OPD_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE opd ADD OPD_CREATE_DATE datetime NULL;
ALTER TABLE opd ADD OPD_MODIFY_DATE datetime NULL;

ALTER TABLE therapies ADD THR_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE therapies ADD THR_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE therapies ADD THR_CREATE_DATE datetime NULL;
ALTER TABLE therapies ADD THR_MODIFY_DATE datetime NULL;

ALTER TABLE user ADD US_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE user ADD US_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE user ADD US_CREATE_DATE datetime NULL;
ALTER TABLE user ADD US_MODIFY_DATE datetime NULL;

ALTER TABLE patient ADD PAT_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE patient ADD PAT_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE patient ADD PAT_CREATE_DATE datetime NULL;
ALTER TABLE patient ADD PAT_MODIFY_DATE datetime NULL;

ALTER TABLE pregnancyvisit ADD PVIS_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE pregnancyvisit ADD PVIS_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE pregnancyvisit ADD PVIS_CREATE_DATE datetime NULL;
ALTER TABLE pregnancyvisit ADD PVIS_MODIFY_DATE datetime NULL;

ALTER TABLE patientvaccine ADD PAV_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE patientvaccine ADD PAV_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE patientvaccine ADD PAV_CREATE_DATE datetime NULL;
ALTER TABLE patientvaccine ADD PAV_MODIFY_DATE datetime NULL;

ALTER TABLE pregnancy ADD PREG_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE pregnancy ADD PREG_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE pregnancy ADD PREG_CREATE_DATE datetime NULL;
ALTER TABLE pregnancy ADD PREG_MODIFY_DATE datetime NULL;

ALTER TABLE pregnancydelivery ADD PDEL_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE pregnancydelivery ADD PDEL_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE pregnancydelivery ADD PDEL_CREATE_DATE datetime NULL;
ALTER TABLE pregnancydelivery ADD PDEL_MODIFY_DATE datetime NULL;

ALTER TABLE visits ADD VST_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE visits ADD VST_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE visits ADD VST_CREATE_DATE datetime NULL;
ALTER TABLE visits ADD VST_MODIFY_DATE datetime NULL;

ALTER TABLE prices ADD PRC_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE prices ADD PRC_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE prices ADD PRC_CREATE_DATE datetime NULL;
ALTER TABLE prices ADD PRC_MODIFY_DATE datetime NULL;

ALTER TABLE pricelists ADD LST_CREATE_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE pricelists ADD LST_MODIFY_BY varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT "";
ALTER TABLE pricelists ADD LST_CREATE_DATE datetime NULL;
ALTER TABLE pricelists ADD LST_MODIFY_DATE datetime NULL;

ALTER TABLE laboratory ADD LAB_PRESCRIBER varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;









