
INSERT INTO parameters (PRMS_CODE, PRMS_VALUE, PRMS_DEFAULT_VALUE, PRMS_DESCRIPTION, PRMS_CREATE_BY, PRMS_MODIFY_BY, PRMS_CREATE_DATE, PRMS_MODIFY_DATE, PRMS_DELETED_BY, PRMS_DELETED_DATE, PRMS_DELETED) VALUES
	('LABORATORYCODE', '', '', 'Laboratory code', 'admin', NULL, '2020-09-24 14:40:28', NULL, NULL, NULL, NULL);

INSERT INTO parameters (PRMS_CODE, PRMS_VALUE, PRMS_DEFAULT_VALUE, PRMS_DESCRIPTION, PRMS_CREATE_BY, PRMS_MODIFY_BY, PRMS_CREATE_DATE, PRMS_MODIFY_DATE, PRMS_DELETED_BY, PRMS_DELETED_DATE, PRMS_DELETED) VALUES
	('ALLOWLABOSTOCKAUTOREMOVAL', '@false', '@false', 'Allow laboratory stock auto removal', 'admin', NULL, '2020-09-24 14:40:28', NULL, NULL, NULL, NULL);




