package org.isf.utils.jobjects;

public class BillItemReportBean {

	private String  BLI_ITEM_DESC;
	private String  BLI_ITEM_GROUP;
	private Double  COUNT_JANUARY;
	private Double  AMOUNT_JANUARY;
	private Double  COUNT_FEBRUARY;
	private Double  AMOUNT_FEBRUARY;
	private Double  COUNT_MARCH;
	private Double  AMOUNT_MARCH;
	private Double  COUNT_APRIL;
	private Double  AMOUNT_APRIL;
	private Double  COUNT_MAY;
	private Double  AMOUNT_MAY;
	private Double  COUNT_JUNE;
	private Double  AMOUNT_JUNE;
	private Double  COUNT_JULY;
	private Double  AMOUNT_JULY;
	private Double  COUNT_AUGUST;
	private Double  AMOUNT_AUGUST;
	private Double  COUNT_SEPTEMBER;
	private Double  AMOUNT_SEPTEMBER;
	private Double  COUNT_OCTOBER;
	private Double  AMOUNT_OCTOBER;
	private Double  COUNT_NOVEMBER;
	private Double  AMOUNT_NOVEMBER;
	private Double  COUNT_DECEMBER;
	private Double  AMOUNT_DECEMBER;
	private Double  TOTAL_YEAR_COUNT;
	private Double  TOTAL_YEAR_AMOUNT;
	
	private Double  REFUNDED_COUNT_JANUARY;
	private Double  REFUNDED_AMOUNT_JANUARY;
	private Double  REFUNDED_COUNT_FEBRUARY;
	private Double  REFUNDED_AMOUNT_FEBRUARY;
	private Double  REFUNDED_COUNT_MARCH;
	private Double  REFUNDED_AMOUNT_MARCH;
	private Double  REFUNDED_COUNT_APRIL;
	private Double  REFUNDED_AMOUNT_APRIL;
	private Double  REFUNDED_COUNT_MAY;
	private Double  REFUNDED_AMOUNT_MAY;
	private Double  REFUNDED_COUNT_JUNE;
	private Double  REFUNDED_AMOUNT_JUNE;
	private Double  REFUNDED_COUNT_JULY;
	private Double  REFUNDED_AMOUNT_JULY;
	private Double  REFUNDED_COUNT_AUGUST;
	private Double  REFUNDED_AMOUNT_AUGUST;
	private Double  REFUNDED_COUNT_SEPTEMBER;
	private Double  REFUNDED_AMOUNT_SEPTEMBER;
	private Double  REFUNDED_COUNT_OCTOBER;
	private Double  REFUNDED_AMOUNT_OCTOBER;
	private Double  REFUNDED_COUNT_NOVEMBER;
	private Double  REFUNDED_AMOUNT_NOVEMBER;
	private Double  REFUNDED_COUNT_DECEMBER;
	private Double  REFUNDED_AMOUNT_DECEMBER;
	private Double  REFUNDED_TOTAL_YEAR_COUNT;
	private Double  REFUNDED_TOTAL_YEAR_AMOUNT;
	
	public BillItemReportBean(){
		BLI_ITEM_DESC = "";
		BLI_ITEM_GROUP = "";
		COUNT_JANUARY = 0.0;
		AMOUNT_JANUARY = 0.0;
		COUNT_FEBRUARY = 0.0;
		AMOUNT_FEBRUARY = 0.0;
		COUNT_MARCH = 0.0;
		AMOUNT_MARCH = 0.0;
		COUNT_APRIL = 0.0;
		AMOUNT_APRIL = 0.0;
		COUNT_MAY = 0.0;
		AMOUNT_MAY = 0.0;
		COUNT_JUNE = 0.0;
		AMOUNT_JUNE = 0.0;
		COUNT_JULY = 0.0;
		AMOUNT_JULY = 0.0;
		COUNT_AUGUST = 0.0;
		AMOUNT_AUGUST = 0.0;
		COUNT_SEPTEMBER = 0.0;
		AMOUNT_SEPTEMBER = 0.0;
		COUNT_OCTOBER = 0.0;
		AMOUNT_OCTOBER = 0.0;
		COUNT_NOVEMBER = 0.0;
		AMOUNT_NOVEMBER = 0.0;
		COUNT_DECEMBER = 0.0;
		AMOUNT_DECEMBER = 0.0;
		TOTAL_YEAR_COUNT = 0.0;
		TOTAL_YEAR_AMOUNT = 0.0;
		
		REFUNDED_COUNT_JANUARY = 0.0;
		REFUNDED_AMOUNT_JANUARY = 0.0;
		REFUNDED_COUNT_FEBRUARY = 0.0;
		REFUNDED_AMOUNT_FEBRUARY = 0.0;
		REFUNDED_COUNT_MARCH = 0.0;
		REFUNDED_AMOUNT_MARCH = 0.0;
		REFUNDED_COUNT_APRIL = 0.0;
		REFUNDED_AMOUNT_APRIL = 0.0;
		REFUNDED_COUNT_MAY = 0.0;
		REFUNDED_AMOUNT_MAY = 0.0;
		REFUNDED_COUNT_JUNE = 0.0;
		REFUNDED_AMOUNT_JUNE = 0.0;
		REFUNDED_COUNT_JULY = 0.0;
		REFUNDED_AMOUNT_JULY = 0.0;
		REFUNDED_COUNT_AUGUST = 0.0;
		REFUNDED_AMOUNT_AUGUST = 0.0;
		REFUNDED_COUNT_SEPTEMBER = 0.0;
		REFUNDED_AMOUNT_SEPTEMBER = 0.0;
		REFUNDED_COUNT_OCTOBER = 0.0;
		REFUNDED_AMOUNT_OCTOBER = 0.0;
		REFUNDED_COUNT_NOVEMBER = 0.0;
		REFUNDED_AMOUNT_NOVEMBER = 0.0;
		REFUNDED_COUNT_DECEMBER = 0.0;
		REFUNDED_AMOUNT_DECEMBER = 0.0;
		REFUNDED_TOTAL_YEAR_COUNT = 0.0;
		REFUNDED_TOTAL_YEAR_AMOUNT = 0.0;
	}
	
	public String getBLI_ITEM_DESC() {
		return BLI_ITEM_DESC;
	}
	public void setBLI_ITEM_DESC(String bLI_ITEM_DESC) {
		BLI_ITEM_DESC = bLI_ITEM_DESC;
	}
	public Double getCOUNT_JANUARY() {
		return COUNT_JANUARY;
	}
	public void setCOUNT_JANUARY(Double cOUNT_JANUARY) {
		COUNT_JANUARY = cOUNT_JANUARY;
	}
	public Double getAMOUNT_JANUARY() {
		return AMOUNT_JANUARY;
	}
	public void setAMOUNT_JANUARY(Double aMOUNT_JANUARY) {
		AMOUNT_JANUARY = aMOUNT_JANUARY;
	}
	public Double getCOUNT_FEBRUARY() {
		return COUNT_FEBRUARY;
	}
	public void setCOUNT_FEBRUARY(Double cOUNT_FEBRUARY) {
		COUNT_FEBRUARY = cOUNT_FEBRUARY;
	}
	public Double getAMOUNT_FEBRUARY() {
		return AMOUNT_FEBRUARY;
	}
	public void setAMOUNT_FEBRUARY(Double aMOUNT_FEBRUARY) {
		AMOUNT_FEBRUARY = aMOUNT_FEBRUARY;
	}
	public Double getCOUNT_MARCH() {
		return COUNT_MARCH;
	}
	public void setCOUNT_MARCH(Double cOUNT_MARCH) {
		COUNT_MARCH = cOUNT_MARCH;
	}
	public Double getAMOUNT_MARCH() {
		return AMOUNT_MARCH;
	}
	public void setAMOUNT_MARCH(Double aMOUNT_MARCH) {
		AMOUNT_MARCH = aMOUNT_MARCH;
	}
	public Double getCOUNT_APRIL() {
		return COUNT_APRIL;
	}
	public void setCOUNT_APRIL(Double cOUNT_APRIL) {
		COUNT_APRIL = cOUNT_APRIL;
	}
	public Double getAMOUNT_APRIL() {
		return AMOUNT_APRIL;
	}
	public void setAMOUNT_APRIL(Double aMOUNT_APRIL) {
		AMOUNT_APRIL = aMOUNT_APRIL;
	}
	public Double getCOUNT_MAY() {
		return COUNT_MAY;
	}
	public void setCOUNT_MAY(Double cOUNT_MAY) {
		COUNT_MAY = cOUNT_MAY;
	}
	public Double getAMOUNT_MAY() {
		return AMOUNT_MAY;
	}
	public void setAMOUNT_MAY(Double aMOUNT_MAY) {
		AMOUNT_MAY = aMOUNT_MAY;
	}
	public Double getCOUNT_JUNE() {
		return COUNT_JUNE;
	}
	public void setCOUNT_JUNE(Double cOUNT_JUNE) {
		COUNT_JUNE = cOUNT_JUNE;
	}
	public Double getAMOUNT_JUNE() {
		return AMOUNT_JUNE;
	}
	public void setAMOUNT_JUNE(Double aMOUNT_JUNE) {
		AMOUNT_JUNE = aMOUNT_JUNE;
	}
	public Double getCOUNT_JULY() {
		return COUNT_JULY;
	}
	public void setCOUNT_JULY(Double cOUNT_JULY) {
		COUNT_JULY = cOUNT_JULY;
	}
	public Double getAMOUNT_JULY() {
		return AMOUNT_JULY;
	}
	public void setAMOUNT_JULY(Double aMOUNT_JULY) {
		AMOUNT_JULY = aMOUNT_JULY;
	}
	public Double getCOUNT_AUGUST() {
		return COUNT_AUGUST;
	}
	public void setCOUNT_AUGUST(Double cOUNT_AUGUST) {
		COUNT_AUGUST = cOUNT_AUGUST;
	}
	public Double getAMOUNT_AUGUST() {
		return AMOUNT_AUGUST;
	}
	public void setAMOUNT_AUGUST(Double aMOUNT_AUGUST) {
		AMOUNT_AUGUST = aMOUNT_AUGUST;
	}
	public Double getCOUNT_SEPTEMBER() {
		return COUNT_SEPTEMBER;
	}
	public void setCOUNT_SEPTEMBER(Double cOUNT_SEPTEMBER) {
		COUNT_SEPTEMBER = cOUNT_SEPTEMBER;
	}
	public Double getAMOUNT_SEPTEMBER() {
		return AMOUNT_SEPTEMBER;
	}
	public void setAMOUNT_SEPTEMBER(Double aMOUNT_SEPTEMBER) {
		AMOUNT_SEPTEMBER = aMOUNT_SEPTEMBER;
	}
	public Double getCOUNT_OCTOBER() {
		return COUNT_OCTOBER;
	}
	public void setCOUNT_OCTOBER(Double cOUNT_OCTOBER) {
		COUNT_OCTOBER = cOUNT_OCTOBER;
	}
	public Double getAMOUNT_OCTOBER() {
		return AMOUNT_OCTOBER;
	}
	public void setAMOUNT_OCTOBER(Double aMOUNT_OCTOBER) {
		AMOUNT_OCTOBER = aMOUNT_OCTOBER;
	}
	public Double getCOUNT_NOVEMBER() {
		return COUNT_NOVEMBER;
	}
	public void setCOUNT_NOVEMBER(Double cOUNT_NOVEMBER) {
		COUNT_NOVEMBER = cOUNT_NOVEMBER;
	}
	public Double getAMOUNT_NOVEMBER() {
		return AMOUNT_NOVEMBER;
	}
	public void setAMOUNT_NOVEMBER(Double aMOUNT_NOVEMBER) {
		AMOUNT_NOVEMBER = aMOUNT_NOVEMBER;
	}
	public Double getCOUNT_DECEMBER() {
		return COUNT_DECEMBER;
	}
	public void setCOUNT_DECEMBER(Double cOUNT_DECEMBER) {
		COUNT_DECEMBER = cOUNT_DECEMBER;
	}
	public Double getAMOUNT_DECEMBER() {
		return AMOUNT_DECEMBER;
	}
	public void setAMOUNT_DECEMBER(Double aMOUNT_DECEMBER) {
		AMOUNT_DECEMBER = aMOUNT_DECEMBER;
	}
	public Double getTOTAL_YEAR_COUNT() {
		return TOTAL_YEAR_COUNT;
	}
	public void setTOTAL_YEAR_COUNT(Double tOTAL_YEAR_COUNT) {
		TOTAL_YEAR_COUNT = tOTAL_YEAR_COUNT;
	}
	public Double getTOTAL_YEAR_AMOUNT() {
		return TOTAL_YEAR_AMOUNT;
	}
	public void setTOTAL_YEAR_AMOUNT(Double tOTAL_YEAR_AMOUNT) {
		TOTAL_YEAR_AMOUNT = tOTAL_YEAR_AMOUNT;
	}
	
	public Double getREFUNDED_COUNT_JANUARY() {
		return REFUNDED_COUNT_JANUARY;
	}
	public void setREFUNDED_COUNT_JANUARY(Double cOUNT_JANUARY) {
		REFUNDED_COUNT_JANUARY = cOUNT_JANUARY;
	}
	public Double getREFUNDED_AMOUNT_JANUARY() {
		return REFUNDED_AMOUNT_JANUARY;
	}
	public void setREFUNDED_AMOUNT_JANUARY(Double aMOUNT_JANUARY) {
		REFUNDED_AMOUNT_JANUARY = aMOUNT_JANUARY;
	}
	public Double getREFUNDED_COUNT_FEBRUARY() {
		return REFUNDED_COUNT_FEBRUARY;
	}
	public void setREFUNDED_COUNT_FEBRUARY(Double cOUNT_FEBRUARY) {
		REFUNDED_COUNT_FEBRUARY = cOUNT_FEBRUARY;
	}
	public Double getREFUNDED_AMOUNT_FEBRUARY() {
		return REFUNDED_AMOUNT_FEBRUARY;
	}
	public void setREFUNDED_AMOUNT_FEBRUARY(Double aMOUNT_FEBRUARY) {
		REFUNDED_AMOUNT_FEBRUARY = aMOUNT_FEBRUARY;
	}
	public Double getREFUNDED_COUNT_MARCH() {
		return REFUNDED_COUNT_MARCH;
	}
	public void setREFUNDED_COUNT_MARCH(Double cOUNT_MARCH) {
		REFUNDED_COUNT_MARCH = cOUNT_MARCH;
	}
	public Double getREFUNDED_AMOUNT_MARCH() {
		return REFUNDED_AMOUNT_MARCH;
	}
	public void setREFUNDED_AMOUNT_MARCH(Double aMOUNT_MARCH) {
		REFUNDED_AMOUNT_MARCH = aMOUNT_MARCH;
	}
	public Double getREFUNDED_COUNT_APRIL() {
		return REFUNDED_COUNT_APRIL;
	}
	public void setREFUNDED_COUNT_APRIL(Double cOUNT_APRIL) {
		REFUNDED_COUNT_APRIL = cOUNT_APRIL;
	}
	public Double getREFUNDED_AMOUNT_APRIL() {
		return REFUNDED_AMOUNT_APRIL;
	}
	public void setREFUNDED_AMOUNT_APRIL(Double aMOUNT_APRIL) {
		REFUNDED_AMOUNT_APRIL = aMOUNT_APRIL;
	}
	public Double getREFUNDED_COUNT_MAY() {
		return REFUNDED_COUNT_MAY;
	}
	public void setREFUNDED_COUNT_MAY(Double cOUNT_MAY) {
		REFUNDED_COUNT_MAY = cOUNT_MAY;
	}
	public Double getREFUNDED_AMOUNT_MAY() {
		return REFUNDED_AMOUNT_MAY;
	}
	public void setREFUNDED_AMOUNT_MAY(Double aMOUNT_MAY) {
		REFUNDED_AMOUNT_MAY = aMOUNT_MAY;
	}
	public Double getREFUNDED_COUNT_JUNE() {
		return REFUNDED_COUNT_JUNE;
	}
	public void setREFUNDED_COUNT_JUNE(Double cOUNT_JUNE) {
		REFUNDED_COUNT_JUNE = cOUNT_JUNE;
	}
	public Double getREFUNDED_AMOUNT_JUNE() {
		return REFUNDED_AMOUNT_JUNE;
	}
	public void setREFUNDED_AMOUNT_JUNE(Double aMOUNT_JUNE) {
		REFUNDED_AMOUNT_JUNE = aMOUNT_JUNE;
	}
	public Double getREFUNDED_COUNT_JULY() {
		return REFUNDED_COUNT_JULY;
	}
	public void setREFUNDED_COUNT_JULY(Double cOUNT_JULY) {
		REFUNDED_COUNT_JULY = cOUNT_JULY;
	}
	public Double getREFUNDED_AMOUNT_JULY() {
		return REFUNDED_AMOUNT_JULY;
	}
	public void setREFUNDED_AMOUNT_JULY(Double aMOUNT_JULY) {
		REFUNDED_AMOUNT_JULY = aMOUNT_JULY;
	}
	public Double getREFUNDED_COUNT_AUGUST() {
		return REFUNDED_COUNT_AUGUST;
	}
	public void setREFUNDED_COUNT_AUGUST(Double cOUNT_AUGUST) {
		REFUNDED_COUNT_AUGUST = cOUNT_AUGUST;
	}
	public Double getREFUNDED_AMOUNT_AUGUST() {
		return REFUNDED_AMOUNT_AUGUST;
	}
	public void setREFUNDED_AMOUNT_AUGUST(Double aMOUNT_AUGUST) {
		REFUNDED_AMOUNT_AUGUST = aMOUNT_AUGUST;
	}
	public Double getREFUNDED_COUNT_SEPTEMBER() {
		return REFUNDED_COUNT_SEPTEMBER;
	}
	public void setREFUNDED_COUNT_SEPTEMBER(Double cOUNT_SEPTEMBER) {
		REFUNDED_COUNT_SEPTEMBER = cOUNT_SEPTEMBER;
	}
	public Double getREFUNDED_AMOUNT_SEPTEMBER() {
		return REFUNDED_AMOUNT_SEPTEMBER;
	}
	public void setREFUNDED_AMOUNT_SEPTEMBER(Double aMOUNT_SEPTEMBER) {
		REFUNDED_AMOUNT_SEPTEMBER = aMOUNT_SEPTEMBER;
	}
	public Double getREFUNDED_COUNT_OCTOBER() {
		return REFUNDED_COUNT_OCTOBER;
	}
	public void setREFUNDED_COUNT_OCTOBER(Double cOUNT_OCTOBER) {
		REFUNDED_COUNT_OCTOBER = cOUNT_OCTOBER;
	}
	public Double getREFUNDED_AMOUNT_OCTOBER() {
		return REFUNDED_AMOUNT_OCTOBER;
	}
	public void setREFUNDED_AMOUNT_OCTOBER(Double aMOUNT_OCTOBER) {
		REFUNDED_AMOUNT_OCTOBER = aMOUNT_OCTOBER;
	}
	public Double getREFUNDED_COUNT_NOVEMBER() {
		return REFUNDED_COUNT_NOVEMBER;
	}
	public void setREFUNDED_COUNT_NOVEMBER(Double cOUNT_NOVEMBER) {
		REFUNDED_COUNT_NOVEMBER = cOUNT_NOVEMBER;
	}
	public Double getREFUNDED_AMOUNT_NOVEMBER() {
		return REFUNDED_AMOUNT_NOVEMBER;
	}
	public void setREFUNDED_AMOUNT_NOVEMBER(Double aMOUNT_NOVEMBER) {
		REFUNDED_AMOUNT_NOVEMBER = aMOUNT_NOVEMBER;
	}
	public Double getREFUNDED_COUNT_DECEMBER() {
		return REFUNDED_COUNT_DECEMBER;
	}
	public void setREFUNDED_COUNT_DECEMBER(Double cOUNT_DECEMBER) {
		REFUNDED_COUNT_DECEMBER = cOUNT_DECEMBER;
	}
	public Double getREFUNDED_AMOUNT_DECEMBER() {
		return REFUNDED_AMOUNT_DECEMBER;
	}
	public void setREFUNDED_AMOUNT_DECEMBER(Double aMOUNT_DECEMBER) {
		REFUNDED_AMOUNT_DECEMBER = aMOUNT_DECEMBER;
	}
	public Double getREFUNDED_TOTAL_YEAR_COUNT() {
		return REFUNDED_TOTAL_YEAR_COUNT;
	}
	public void setREFUNDED_TOTAL_YEAR_COUNT(Double tOTAL_YEAR_COUNT) {
		REFUNDED_TOTAL_YEAR_COUNT = tOTAL_YEAR_COUNT;
	}
	public Double getREFUNDED_TOTAL_YEAR_AMOUNT() {
		return REFUNDED_TOTAL_YEAR_AMOUNT;
	}
	public void setREFUNDED_TOTAL_YEAR_AMOUNT(Double tOTAL_YEAR_AMOUNT) {
		REFUNDED_TOTAL_YEAR_AMOUNT = tOTAL_YEAR_AMOUNT;
	}
	
	public String getBLI_ITEM_GROUP() {
		return BLI_ITEM_GROUP;
	}

	public void setBLI_ITEM_GROUP(String bLI_ITEM_GROUP) {
		BLI_ITEM_GROUP = bLI_ITEM_GROUP;
	}

}
